// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  helpSidebar: [
    {
      type: 'autogenerated',
      dirName: 'help',
    },
  ],
  articleSidebar: [
    {
      type: 'autogenerated',
      dirName: 'article',
    },
  ],
};

export default sidebars;
